### ISSUE TITLE
Additional installation instructions?

### ISSUE THREAD

**Issue by abhisheknaik96** [jacotay7/pyRTC#11]
Hello,

   Thank you for creating this library! 

However, while trying to set it up, I ran into several issues. For instance, when trying to run the example jupyter notebook, it isn't clear what is `/Lib` or `/Lib64` and where it should be added. I commented it out for now. Additionally, after installing `OOPAO`, I had to manually pip-install the following packages: `pipython`, `rotpy`, `mpmath`. The notebook also required `ximea`, which isn't a pip package yet, so I removed the `ximeaWFS.py` file for now. 

Perhaps I missed some installation instructions somewhere?

**Comment by jacotay7** [comment]
@abhisheknaik96 I pulled in a ton of changes to main and confirmed that the example ran in a new environment on my local machine (ubuntu 22.04, python 3.11). Let me know how if you keep having issues, happy to help!

**Comment by abhisheknaik96** [comment]
Thank you Jacob for the prompt response! I have to set this up on a new machine soon, so I'll test the new changes then. Thanks again!
